#!/usr/bin/env python3

"""
Generate the figure for the segmentation and registration results.
"""
import sys
import os
import utils

# the images of each subject are generated by 11_sl_seg_reg_visualizations.sh

studyDataDir = sys.argv[1]
subjects = utils.subjects()


figure_dir = f'{studyDataDir}/derivatives/figures/'
os.makedirs(figure_dir, exist_ok=True)

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# plot parameters and initalization
utils.setup_figure_style()

# compose the figure

# create a figure with one panel for each of the 21 subjects in a 3x7 grid
# define the figure, set size
fig, axs = plt.subplots(3, 7, figsize=(15, 7))

# load the images
for i, subject in enumerate(subjects):
    seg_reg_vis_dir = os.path.join(studyDataDir, 'derivatives', 'seg_reg_vis', subject)
    img = mpimg.imread(os.path.join(seg_reg_vis_dir,f'seg-reg-vis_{subject}_opaque.png'))
    axs[i//7, i%7].imshow(img)
    axs[i//7, i%7].axis('off')
    axs[i//7, i%7].set_title(f'Subject {int(subject[4:])}')

# annotate the figure and make publication ready
plt.tight_layout()
utils.save_figure(fig, figure_dir, 'figure_seg-reg')

# close the figure
plt.close()


# figure legend:
# Segmentation and registration results for 21 subjects. For each subject the VASO slab (VASO T1w image) is
# superimposed on the T1w image obtained from MP2RAGE, transformed into functional space. The reconstructed pial
# and white matter surfaces are shown in red and blue, respectively. The main ROI, separated into superficial (red)
# and deep (blue) layers, is shown superimposed on the VASO slab.