#!/usr/bin/env python3

"""
Generate the figure for the qualitative comparison of ROI sizes.
"""
import sys
import os
import re
import utils

# the images of each subject are generated by 10_sl_roi-generation_visualization.sh

studyDataDir = sys.argv[1]
subjects = utils.subjects()


figure_dir = f'{studyDataDir}/derivatives/figures/'
os.makedirs(figure_dir, exist_ok=True)

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.gridspec import GridSpec, GridSpecFromSubplotSpec

# plot parameters and initalization
utils.setup_figure_style()

# compose the figure

# ROI target areas visualized in 10_sl_roi-generation_visualization.sh (from its output images)
vis_dir = os.path.join(studyDataDir, 'derivatives', 'roi-generation_vis', subjects[0])
areas = sorted(int(m.group(1)) for fname in os.listdir(vis_dir)
               if (m := re.fullmatch(rf'layer-roi-vol-vis_A(\d+)_{subjects[0]}\.png', fname)))

# figsize targets an A4 page in Word with 1" margins (6.3" content width),
# leaving room below the figure for a short caption (9.69" content height).
fig = plt.figure(figsize=(6.3, 8.5))
# Outer grid: one row per area, with a visible gap between sections.
# Each section then gets its own tightly-spaced inner 3x7 (+label) grid.
outer_gs = GridSpec(len(areas), 1, figure=fig, hspace=0.15)

for section, area in enumerate(areas):
    inner_gs = GridSpecFromSubplotSpec(
        3, 8, subplot_spec=outer_gs[section],
        width_ratios=[0.06] + [1] * 7, wspace=0.05, hspace=0.25)

    label_ax = fig.add_subplot(inner_gs[:, 0])
    label_ax.axis('off')
    label_ax.text(0.5, 0.5, f'{area} mm²', rotation=90,
                  ha='center', va='center', fontsize=10,
                  transform=label_ax.transAxes)

    for i, subject in enumerate(subjects):
        roi_generation_vis_dir = os.path.join(studyDataDir, 'derivatives','roi-generation_vis', subject)
        img = mpimg.imread(os.path.join(roi_generation_vis_dir,f'layer-roi-vol-vis_A{area}_{subject}.png'))
        ax = fig.add_subplot(inner_gs[i // 7, 1 + i % 7])
        ax.imshow(img)
        ax.axis('off')
        # small pad keeps the title hugging its own image, not the row above
        ax.set_title(f'Subject {int(subject[4:])}', fontsize=6, pad=2)

# annotate the figure and make publication ready
utils.save_figure(fig, figure_dir, 'figure_roi-size-vis_comparison', dpi=300)

plt.close()


# figure legend:
# Layer ROIs of all 21 subjects for the three ROI target areas (50, 100 and 200 mm², top to bottom).
# For each subject, the ROI separated into superficial (red) and deep (blue) layers is shown on an axial
# slice through its center of gravity of the T1w image obtained from MP2RAGE, transformed into functional space.